-- Feed follow feature support table.
CREATE TABLE IF NOT EXISTS public.user_follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  following_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_follows_not_self CHECK (user_id <> following_id),
  CONSTRAINT user_follows_unique_pair UNIQUE (user_id, following_id)
);

CREATE INDEX IF NOT EXISTS user_follows_user_id_idx
  ON public.user_follows (user_id);

CREATE INDEX IF NOT EXISTS user_follows_following_id_idx
  ON public.user_follows (following_id);

ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

-- Reader can only access own follow rows.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'user_follows'
      AND policyname = 'user_follows_select_own'
  ) THEN
    CREATE POLICY user_follows_select_own
      ON public.user_follows
      FOR SELECT
      USING (auth.uid() = user_id OR auth.uid() = following_id);
  END IF;
END $$;

-- Authenticated user can follow from own account only.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'user_follows'
      AND policyname = 'user_follows_insert_own'
  ) THEN
    CREATE POLICY user_follows_insert_own
      ON public.user_follows
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- Authenticated user can unfollow from own account only.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'user_follows'
      AND policyname = 'user_follows_delete_own'
  ) THEN
    CREATE POLICY user_follows_delete_own
      ON public.user_follows
      FOR DELETE
      USING (auth.uid() = user_id);
  END IF;
END $$;
